#!/bin/bash

PROJECT_NAME=$1
PROJECT_PATH="$PROJECT_NAME/ios/"

gem install earlgrey
cp scripts/test-utils/SetupTests.m $PROJECT_PATH/SetupTests

pushd $PROJECT_PATH
  brew update
  brew install carthage
  echo 'github "google/EarlGrey" "1.15.0"' > Cartfile.private
  carthage bootstrap --platform ios
  earlgrey install -t SetupTests
popd
