#!/bin/bash

set -eo pipefail

RN_VERSION=$1
DESTINATION=$(dirname $2)
PROJECT_NAME=$(basename $2)

pushd $DESTINATION

react-native init --version="$RN_VERSION" $PROJECT_NAME

pushd $PROJECT_NAME
yarn add ../..                          # install react-native-ble-plx
react-native link react-native-ble-plx  # and link it
rm -rf node_modules/react-native-ble-plx/node_modules
rm -rf node_modules/react-native-ble-plx/integration-tests

FLOW_VERSION=$(../scripts/get-flow-version)
popd

scripts/patch-project $RN_VERSION
scripts/enable-swift $PROJECT_NAME

popd

CURRENT_FLOW_VERSION=$(integration-tests/scripts/get-flow-version)

echo "Change flow $CURRENT_FLOW_VERSION -> $FLOW_VERSION..."
# replace flow version with what's in generated project
awk -v current="$CURRENT_FLOW_VERSION" -v new="$FLOW_VERSION" '
  function escape_pattern(pat,   safe) {
    safe = pat
    gsub(/[][^$.*?+{}\\()|]/, "\\\\&", safe)
    return safe
  }
  { gsub(escape_pattern(current, ""), new); print }' .flowconfig > .flowconfig.new
cat .flowconfig.new
mv .flowconfig.new .flowconfig

npm install flow-bin@$FLOW_VERSION
