#!/bin/bash

set -eo pipefail

RN_VERSION=$1
DESTINATION=$(dirname $2)
PROJECT_NAME=$(basename $2)

# pack current react-native-ble-plx
npm pack

pushd $DESTINATION

react-native init --version="$RN_VERSION" $PROJECT_NAME

pushd $PROJECT_NAME

# install react-native-ble-plx
tar -xzvf ../../react-native-ble-plx-*.tgz
mv package node_modules/react-native-ble-plx

react-native link react-native-ble-plx  # and link it

FLOW_VERSION=$(../scripts/get-flow-version)
npm install flow-bin@$FLOW_VERSION

rm -rf ../../node_modules

popd

scripts/patch-project $RN_VERSION
scripts/enable-swift $PROJECT_NAME
scripts/add-espresso-tests $PROJECT_NAME

popd
