#!/bin/bash

set -eo pipefail

RN_VERSION=$1
DESTINATION=$(dirname $2)
PROJECT_NAME=$(basename $2)

pushd $DESTINATION

react-native init --version="$RN_VERSION" $PROJECT_NAME

pushd $PROJECT_NAME

FLOW_VERSION=$(../scripts/get-flow-version)
yarn add flow-bin@$FLOW_VERSION --dev

# install react-native-ble-plx using the github commit

yarn add https://github.com/Polidea/react-native-ble-plx#$TRAVIS_COMMIT

react-native link react-native-ble-plx  # and link it

rm -rf ../../node_modules

popd

scripts/patch-project $RN_VERSION
scripts/enable-swift $PROJECT_NAME
scripts/add-espresso-tests $PROJECT_NAME

popd
