#!/usr/bin/env ruby

require 'xcodeproj'

require 'pry'

project_name = ARGV[0]
project_path = "#{project_name}/ios/"

project = Xcodeproj::Project.open("#{project_path}/#{project_name}.xcodeproj")

project['Libraries'].new_reference(File.absolute_path("#{project_path}/EarlGrey/EarlGrey-1.15.0/EarlGrey.xcodeproj"))

earl_grey_project = Xcodeproj::Project.open("#{project_path}/EarlGrey/EarlGrey-1.15.0/EarlGrey.xcodeproj")
earl_grey_framework = earl_grey_project.products[0]

binding.pry

# earl_grey_xcodeproj = project.new_file("#{project_path}/EarlGrey/EarlGrey-1.15.0/EarlGrey.xcodeproj")
# earl_grey_framework = project.new_file("#{project_path}/EarlGrey/EarlGrey-1.15.0/EarlGrey.xcodeproj")


project.targets.each do |target|
  # target.add_file_references []

  if target.name == "#{project_name}Tests"
    puts target.name
    target.add_file_references [earl_grey_framework]
  end
end

project.save
