#!/bin/bash

# taken from https://github.com/mmcc007/test_emulators

sh -e /etc/init.d/xvfb start
sleep 3 # give xvfb some time to start

# Install android tools
ANDROID_TOOLS=4333796 # android-28

wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
rm android-sdk-tools.zip
PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools

mkdir -p ~/.android
touch ~/.android/repositories.cfg

# Accept licenses before installing components, no need to echo y for each component
yes | sdkmanager --licenses
# Platform tools
sdkmanager "emulator" "tools" "platform-tools" > /dev/null
sdkmanager --list | head -15

# Install older build tools (for emulator)
sdkmanager "build-tools;28.0.3" "build-tools;25.0.2" "platforms;android-28" "platforms;android-25" > /dev/null

# Create and start emulator.
sdkmanager "system-images;android-$SYS;$ABI" > /dev/null
sdkmanager --list | head -15
echo no | avdmanager create avd -n test -k "system-images;android-$SYS;$ABI"

# Start emulator
$ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &
