package org.konradkrakowiak.blereactnative;

interface ErrorKey {

    /**
     * According to React Native documentation {@link com.facebook.react.bridge.Promise#reject(String)}
     */
    String CODE = "EUNSPECIFIED";

    String NO_CLIENT = "NO_CLIENT";
    String BLUETOOTH_CANNOT_START = "BLUETOOTH_CANNOT_START";
    String BLUETOOTH_DISABLED = "BLUETOOTH_DISABLED";
    String BLUETOOTH_NOT_AVAILABLE = "BLUETOOTH_NOT_AVAILABLE";
    String LOCATION_PERMISSION_MISSING = "LOCATION_PERMISSION_MISSING";
    String LOCATION_SERVICES_DISABLED = "LOCATION_SERVICES_DISABLED";
    String NO_DEVICE_FOUND = "NO_DEVICE_FOUND";
    String BLE_ALREADY_CONNECTED_EXCEPTION = "BLE_ALREADY_CONNECTED_EXCEPTION";
    String BLE_CHARACTERISTIC_NOT_FOUND_EXCEPTION = "BLE_CHARACTERISTIC_NOT_FOUND_EXCEPTION";
    String BLE_GATT_CANNOT_START_EXCEPTION = "BLE_GATT_CANNOT_START_EXCEPTION";
    String BLE_GATT_EXCEPTION = "BLE_GATT_EXCEPTION";
    String UNKNOWN_ERROR = "UNKNOWN_ERROR";
    String NO_CONNECTION = "NO_CONNECTION";
    String BLE_CANNOT_SET_CHARACTERISTIC_NOTIFICATION_EXCEPTION = "BLE_CANNOT_SET_CHARACTERISTIC_NOTIFICATION_EXCEPTION";
}
