
export const DEVICES_SCENE = 'DEVICES_SCENE';
export const SERVICES_SCENE = 'SERVICES_SCENE';
export const CHARACTERISTICS_SCENE = 'CHARACTERISTICS_SCENE';
export const CHARACTERISTIC_DETAILS_SCENE = 'CHARACTERISTIC_DETAILS_SCENE';